In [2]:
import numpy as np

In [4]:
A = np.matrix('1 2; 3 4; 5 6')
B = np.matrix('2 0; 3 2')
x = np.matrix('2; 3')

In [12]:
print("Ax =") 
print(np.matmul(A, x))

Ax =
[[ 8]
 [18]
 [28]]


In [13]:
print("A^T =") 
print(np.transpose(A))

A^T =
[[1 3 5]
 [2 4 6]]


In [14]:
print("AB =") 
print(np.matmul(A, B))

AB =
[[ 8  4]
 [18  8]
 [28 12]]


In [15]:
print("B^-1 =") 
print(np.linalg.inv(B))

B^-1 =
[[ 0.5   0.  ]
 [-0.75  0.5 ]]


In [5]:
# solve for u: x=Bu
print("checking")
u = np.matrix('1; 0')
print(np.matmul(B, u))

checking
[[2]
 [3]]
